#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx limit_includes',
            source='encode_decode_using_coefficients.c',
            target='encode_decode_using_coefficients',
            use=['kodo_rlnc_c_static'])
