// Copyright Steinwurf ApS 2018.
// Distributed under the "STEINWURF EVALUATION LICENSE 1.0".
// See accompanying file LICENSE.rst or
// http://www.steinwurf.com/licensing

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include <kodo_rlnc_c/encoder.h>
#include <kodo_rlnc_c/decoder.h>

/// @example decoded_symbols.c
///
/// Example showing how to process original symbols that were transmitted
/// without kodo headers. These symbols are inserted manually to the decoder
/// before the coded packets are processed.

int main()
{
    // Seed random number generator to produce different results every time
    srand(time(NULL));

    // Set the number of symbols (i.e. the generation size in RLNC
    // terminology) and the size of a symbol in bytes
    uint32_t symbols = 10;
    uint32_t symbol_size = 100;

    // Here we select the finite field to use.
    // Some common choices are: krlnc_binary, krlnc_binary4, krlnc_binary8
    int32_t finite_field = krlnc_binary;

    krlnc_encoder_t encoder = krlnc_create_encoder(
        finite_field, symbols, symbol_size);

    krlnc_decoder_t decoder = krlnc_create_decoder(
        finite_field, symbols, symbol_size);

    // In this example, we do not use systematic coding. The original symbols
    // will be transferred to the decoder without using kodo.
    //
    // We explicitly turn off the systematic mode on the encoder:
    if (krlnc_encoder_is_systematic_on(encoder))
    {
        krlnc_encoder_set_systematic_off(encoder);
    }
    printf("Systematic encoding disabled\n");

    uint32_t bytes_used;
    uint32_t payload_size = krlnc_encoder_max_payload_size(encoder);
    uint8_t* payload = (uint8_t*) malloc(payload_size);

    // Allocate symbols in non-contiguous buffers
    uint8_t** input_symbols = (uint8_t**) malloc(symbols * sizeof(uint8_t*));
    uint8_t** output_symbols = (uint8_t**) malloc(symbols * sizeof(uint8_t*));

    uint32_t i, j;
    // Create the random original symbols and allocate storage for them
    for (i = 0; i < symbols; ++i)
    {
        // Create the individual symbols for the encoder
        input_symbols[i] = (uint8_t*) malloc(symbol_size);

        // Randomize input data
        for (j = 0; j < symbol_size; ++j)
            input_symbols[i][j] = rand() % 256;

        // Store the symbol pointer in the encoder
        krlnc_encoder_set_symbol_storage(
            encoder, input_symbols[i], i);

        // Create the output symbol buffers for the decoder
        output_symbols[i] = (uint8_t*) malloc(symbol_size);

        // Specify the output buffers used for decoding
        krlnc_decoder_set_symbol_storage(
            decoder, output_symbols[i], i);
    }

    // Copy the original symbols to the decoder with some losses
    uint32_t lost_payloads = 0;
    for (i = 0; i < symbols; ++i)
    {
        // Simulate a channel with a 50% loss rate
        if (rand() % 2)
        {
            lost_payloads++;
            printf("Symbol %d lost on channel\n", i);
            continue;
        }

        // If the symbol is not lost, insert that symbol into the decoder
        // using the raw symbol data (no additional headers are needed).
        // This will copy the data from input_symbols[i] to output_symbols[i]
        krlnc_decoder_consume_systematic_symbol(decoder, input_symbols[i], i);
        printf("Symbol %d added to decoder\n", i);
    }

    printf("Number of lost payloads: %d\n\n", lost_payloads);

    // Now we generate coded packets with the encoder in order to recover the
    // lost packets on the decoder side
    while (!krlnc_decoder_is_complete(decoder))
    {
        // The encoder will use a certain amount of bytes of the payload
        // buffer. It will never use more than payload_size, but it might
        // use less.
        bytes_used = krlnc_encoder_produce_payload(encoder, payload);
        printf("Payload generated by encoder, rank = %d, bytes used = %d\n",
               krlnc_encoder_rank(encoder), bytes_used);

        // Pass the coded packet to the decoder
        krlnc_decoder_consume_payload(decoder, payload);
        printf("Payload processed by decoder, current rank = %d\n\n",
               krlnc_decoder_rank(decoder));
    }

    // Compare the input and output symbols one-by-one
    uint32_t failures = 0;
    for (i = 0; i < symbols; ++i)
    {
        if (memcmp(input_symbols[i], output_symbols[i], symbol_size) != 0)
        {
            printf("Error: Symbol %d was not decoded correctly\n", i);
            failures++;
        }

        free(input_symbols[i]);
        free(output_symbols[i]);
    }

    if (failures == 0)
    {
        printf("Data decoded correctly\n");
    }

    free(input_symbols);
    free(output_symbols);
    free(payload);

    krlnc_delete_encoder(encoder);
    krlnc_delete_decoder(decoder);

    return 0;
}
