#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx limit_includes',
            source='uncoded_symbols.c',
            target='uncoded_symbols',
            use=['kodo_rlnc_c_static'])
