#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx limit_includes',
            source='use_trace_layers.c',
            target='use_trace_layers',
            use=['kodo_rlnc_c_static'])
