#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx limit_includes',
            source='encode_decode_on_the_fly.c',
            target='encode_decode_on_the_fly',
            use=['kodo_rlnc_c_static'])
