#! /usr/bin/env python
# encoding: utf-8

static_libs = []

if bld.is_mkspec_platform('windows'):
    static_libs = ['Ws2_32']

bld.program(features='cxx limit_includes',
            source='udp_sender.c',
            target='udp_sender',
            lib=static_libs,
            use=['kodo_rlnc_c_static'])

bld.program(features='cxx limit_includes',
            source='udp_receiver.c',
            target='udp_receiver',
            lib=static_libs,
            use=['kodo_rlnc_c_static'])
