#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx limit_includes',
            source='symbol_status_updater.c',
            target='symbol_status_updater',
            use=['kodo_rlnc_c_static'])
