#! /usr/bin/env python
# encoding: utf-8

bld.program(features='cxx limit_includes',
            source='encode_decode_simple.c',
            target='encode_decode_simple',
            use=['kodo_rlnc_c_static'])
